# Setup

In [34]:
import pandas as pd

# Read in CSVs

In [35]:
alcohol_csv = "HappinessAlcoholConsumption.csv"
country_abbr_csv = "country_abbr.csv"
countries_csv = 'countries.csv'

coords_df = pd.read_csv(countries_csv)
alcohol_df = pd.read_csv(alcohol_csv)
country_df = pd.read_csv(country_abbr_csv)

# Rename 'Name' Column to 'Country'

In [36]:
country_df.columns = ["Country", "Abbreviation"]

alcohol_df
# country_df

,Country,Region,Hemisphere,HappinessScore,HDI,GDP_PerCapita,Beer_PerCapita,Spirit_PerCapita,Wine_PerCapita
0,Denmark,Western Europe,north,7.526,928,53.579,224,81,278
1,Switzerland,Western Europe,north,7.509,943,79.866,185,100,280
2,Iceland,Western Europe,north,7.501,933,60.530,233,61,78
3,Norway,Western Europe,north,7.498,951,70.890,169,71,129
4,Finland,Western Europe,north,7.413,918,43.433,263,133,97
5,Canada,North America,north,7.404,922,42.349,240,122,100
6,Netherlands,Western Europe,north,7.339,928,45.638,251,88,190
7,New Zealand,Australia and New Zealand,south,7.334,915,40.332,203,79,175
8,Australia,Australia and New Zealand,south,7.313,938,49.897,261,72,212
9,Sweden,Western Europe,north,7.291,932,51.845,152,60,186
10,Israel,Middle East and Northern Africa,north,7.267,902,37.181,63,69,9
11,Austria,Western Europe,north,7.119,906,44.731,279,75,191
12,United States,North America,north,7.104,922,57.589,249,158,84
13,Costa Rica,Latin America and Caribbean,north,7.087,791,11.733,149,87,11
14,Germany,Western Europe,north,6.994,934,42.233,346,117,175
15,Brazil,Latin America and Caribbean,both,6.952,758,8.639,245,145,16
16,Belgium,Western Europe,north,6.929,915,41.261,295,84,212
17,Ireland,Western Europe,north,6.907,934,64.100,313,118,165
18,Luxembourg,Western Europe,north,6.871,904,100.739,236,133,271
19,Mexico,Latin America and Caribbean,north,6.778,772,8.444,238,68,5
20,Singapore,Southeastern Asia,north,6.739,930,55.243,60,12,11
21,United Kingdom,Western Europe,north,6.725,920,40.412,219,126,195
22,Chile,Latin America and Caribbean,south,6.705,842,13.961,130,124,172
23,Panama,Latin America and Caribbean,north,6.701,785,14.333,285,104,18
24,Argentina,Latin America and Caribbean,south,6.650,822,12.654,193,25,221
25,Czech Republic,Central and Eastern Europe,north,6.596,885,18.484,361,170,134
26,United Arab Emirates,Middle East and Northern Africa,north,6.573,862,38.518,16,135,5
27,Uruguay,Latin America and Caribbean,south,6.545,802,15.298,115,35,220
28,Malta,Western Europe,north,6.488,875,24.771,149,100,120
29,Colombia,Latin America and Caribbean,both,6.481,747,5.757,159,76,3
...,...,...,...,...,...,...,...,...,...
92,South Africa,Sub-Saharan Africa,south,4.459,696,5.280,225,76,81
93,Egypt,Middle East and Northern Africa,north,4.362,694,3.548,6,4,1
94,Armenia,Central and Eastern Europe,north,4.360,749,3.606,21,179,11
95,Kenya,Sub-Saharan Africa,both,4.356,585,1.463,58,22,2
96,Ukraine,Central and Eastern Europe,north,4.324,746,2.186,206,237,45
97,Ghana,Sub-Saharan Africa,north,4.276,588,1.517,31,3,10
98,Dem. Rep. Congo,Sub-Saharan Africa,south,4.272,452,1.712,32,3,1
99,Georgia,Central and Eastern Europe,north,4.252,776,3.866,52,100,149
100,Rep. Congo,Sub-Saharan Africa,south,4.236,612,498.000,76,1,9
101,Senegal,Sub-Saharan Africa,north,4.219,499,953.000,9,1,7
102,Bulgaria,Central and Eastern Europe,north,4.217,810,7.469,231,252,94
103,Zimbabwe,Sub-Saharan Africa,south,4.193,532,1.029,64,18,4
104,Malawi,Sub-Saharan Africa,south,4.156,474,300.000,8,11,1
105,Gabon,Sub-Saharan Africa,south,4.121,698,7.079,347,98,59
106,Mali,Sub-Saharan Africa,north,4.073,421,780.000,5,1,1
107,Haiti,Latin America and Caribbean,north,4.028,496,735.000,1,326,1
108,Botswana,Sub-Saharan Africa,south,3.974,712,6.954,173,35,35
109,Comoros,Sub-Saharan Africa,south,3.956,502,775.000,1,3,1
110,Cote d'Ivoire,Sub-Saharan Africa,north,3.916,486,1.535,37,1,7
111,Cambodia,Southeastern Asia,north,3.907,576,1.270,57,65,1
112,Angola,Sub-Saharan Africa,south,3.866,577,3.309,217,57,45
113,Niger,Sub-Saharan Africa,north,3.856,351,368.000,3,2,1
114,Chad,Sub-Saharan Africa,north,3.763,405,651.000,15,1,1
115,Burkina Faso,Sub-Saharan Africa,north,3.739,420,614.000,25,7,7
116,Madagascar,Sub-Saharan Africa,south,3.695,517,402.000,26,15,4
117,Tanzania,Sub-Saharan Africa,south,3.666,533,878.000,36,6,1
118,Liberia,Sub-Saharan Africa,north,3.622,432,455.000,19,152,2
119,Benin,Sub-Saharan Africa,north,3.484,512,789.000,34,4,13
120,Togo,Sub-Saharan Africa,north,3.303,500,577.000,36,2,19
121,Syria,Middle East and Northern Africa,north,3.069,536,2.058,5,35,16

In [37]:
coords_df.head()
coords_df.dropna()
coords_df = coords_df.drop(["country"], axis = 1)
coords_df = coords_df.rename(columns = {'name': 'Country'})
coords_df.head()

    latitude  longitude               Country
0  42.546245   1.601554               Andorra
1  23.424076  53.847818  United Arab Emirates
2  33.939110  67.709953           Afghanistan
3  17.060816 -61.796428   Antigua and Barbuda
4  18.220554 -63.068615              Anguilla

In [38]:
country2_df = pd.merge(country_df, coords_df, on = "Country")
country2_df.head()

          Country Abbreviation   latitude   longitude
0     Afghanistan           AF  33.939110   67.709953
1         Albania           AL  41.153332   20.168331
2         Algeria           DZ  28.033886    1.659626
3  American Samoa           AS -14.270972 -170.132217
4         Andorra           AD  42.546245    1.601554

In [39]:
final_alcohol_df = pd.merge(alcohol_df,
                            country2_df,
                            on="Country")
final_alcohol_df

,Country,Region,Hemisphere,HappinessScore,HDI,GDP_PerCapita,Beer_PerCapita,Spirit_PerCapita,Wine_PerCapita,Abbreviation,latitude,longitude
0,Denmark,Western Europe,north,7.526,928,53.579,224,81,278,DK,56.263920,9.501785
1,Switzerland,Western Europe,north,7.509,943,79.866,185,100,280,CH,46.818188,8.227512
2,Iceland,Western Europe,north,7.501,933,60.530,233,61,78,IS,64.963051,-19.020835
3,Norway,Western Europe,north,7.498,951,70.890,169,71,129,NO,60.472024,8.468946
4,Finland,Western Europe,north,7.413,918,43.433,263,133,97,FI,61.924110,25.748151
5,Canada,North America,north,7.404,922,42.349,240,122,100,CA,56.130366,-106.346771
6,Netherlands,Western Europe,north,7.339,928,45.638,251,88,190,NL,52.132633,5.291266
7,New Zealand,Australia and New Zealand,south,7.334,915,40.332,203,79,175,NZ,-40.900557,174.885971
8,Australia,Australia and New Zealand,south,7.313,938,49.897,261,72,212,AU,-25.274398,133.775136
9,Sweden,Western Europe,north,7.291,932,51.845,152,60,186,SE,60.128161,18.643501
10,Israel,Middle East and Northern Africa,north,7.267,902,37.181,63,69,9,IL,31.046051,34.851612
11,Austria,Western Europe,north,7.119,906,44.731,279,75,191,AT,47.516231,14.550072
12,United States,North America,north,7.104,922,57.589,249,158,84,US,37.090240,-95.712891
13,Costa Rica,Latin America and Caribbean,north,7.087,791,11.733,149,87,11,CR,9.748917,-83.753428
14,Germany,Western Europe,north,6.994,934,42.233,346,117,175,DE,51.165691,10.451526
15,Brazil,Latin America and Caribbean,both,6.952,758,8.639,245,145,16,BR,-14.235004,-51.925280
16,Belgium,Western Europe,north,6.929,915,41.261,295,84,212,BE,50.503887,4.469936
17,Ireland,Western Europe,north,6.907,934,64.100,313,118,165,IE,53.412910,-8.243890
18,Luxembourg,Western Europe,north,6.871,904,100.739,236,133,271,LU,49.815273,6.129583
19,Mexico,Latin America and Caribbean,north,6.778,772,8.444,238,68,5,MX,23.634501,-102.552784
20,Singapore,Southeastern Asia,north,6.739,930,55.243,60,12,11,SG,1.352083,103.819836
21,United Kingdom,Western Europe,north,6.725,920,40.412,219,126,195,GB,55.378051,-3.435973
22,Chile,Latin America and Caribbean,south,6.705,842,13.961,130,124,172,CL,-35.675147,-71.542969
23,Panama,Latin America and Caribbean,north,6.701,785,14.333,285,104,18,PA,8.537981,-80.782127
24,Argentina,Latin America and Caribbean,south,6.650,822,12.654,193,25,221,AR,-38.416097,-63.616672
25,Czech Republic,Central and Eastern Europe,north,6.596,885,18.484,361,170,134,CZ,49.817492,15.472962
26,United Arab Emirates,Middle East and Northern Africa,north,6.573,862,38.518,16,135,5,AE,23.424076,53.847818
27,Uruguay,Latin America and Caribbean,south,6.545,802,15.298,115,35,220,UY,-32.522779,-55.765835
28,Malta,Western Europe,north,6.488,875,24.771,149,100,120,MT,35.937496,14.375416
29,Colombia,Latin America and Caribbean,both,6.481,747,5.757,159,76,3,CO,4.570868,-74.297333
...,...,...,...,...,...,...,...,...,...,...,...,...
80,Zambia,Sub-Saharan Africa,south,4.795,586,1.263,32,19,4,ZM,-13.133897,27.849332
81,Albania,Central and Eastern Europe,north,4.655,782,4.132,89,132,54,AL,41.153332,20.168331
82,Sierra Leone,Sub-Saharan Africa,north,4.635,413,481.000,25,3,2,SL,8.460555,-11.779889
83,Namibia,Sub-Saharan Africa,south,4.574,645,4.561,376,3,1,NaN,-22.957640,18.490410
84,Cameroon,Sub-Saharan Africa,south,4.513,553,1.375,147,1,4,CM,7.369722,12.354722
85,South Africa,Sub-Saharan Africa,south,4.459,696,5.280,225,76,81,ZA,-30.559482,22.937506
86,Egypt,Middle East and Northern Africa,north,4.362,694,3.548,6,4,1,EG,26.820553,30.802498
87,Armenia,Central and Eastern Europe,north,4.360,749,3.606,21,179,11,AM,40.069099,45.038189
88,Kenya,Sub-Saharan Africa,both,4.356,585,1.463,58,22,2,KE,-0.023559,37.906193
89,Ukraine,Central and Eastern Europe,north,4.324,746,2.186,206,237,45,UA,48.379433,31.165580
90,Ghana,Sub-Saharan Africa,north,4.276,588,1.517,31,3,10,GH,7.946527,-1.023194
91,Georgia,Central and Eastern Europe,north,4.252,776,3.866,52,100,149,GE,42.315407,43.356892
92,Senegal,Sub-Saharan Africa,north,4.219,499,953.000,9,1,7,SN,14.497401,-14.452362
93,Bulgaria,Central and Eastern Europe,north,4.217,810,7.469,231,252,94,BG,42.733883,25.485830
94,Zimbabwe,Sub-Saharan Africa,south,4.193,532,1.029,64,18,4,ZW,-19.015438,29.154857
95,Malawi,Sub-Saharan Africa,south,4.156,474,300.000,8,11,1,MW,-13.254308,34.301525
96,Gabon,Sub-Saharan Africa,south,4.121,698,7.079,347,98,59,GA,-0.803689,11.609444
97,Mali,Sub-Saharan Africa,north,4.073,421,780.000,5,1,1,ML,17.570692,-3.996166
98,Haiti,Latin America and Caribbean,north,4.028,496,735.000,1,326,1,HT,18.971187,-72.285215
99,Botswana,Sub-Saharan Africa,south,3.974,712,6.954,173,35,35,BW,-22.328474,24.684866
100,Comoros,Sub-Saharan Africa,south,3.956,502,775.000,1,3,1,KM,-11.875001,43.872219
101,Cambodia,Southeastern Asia,north,3.907,576,1.270,57,65,1,KH,12.565679,104.990963
102,Angola,Sub-Saharan Africa,south,3.866,577,3.309,217,57,45,AO,-11.202692,17.873887
103,Niger,Sub-Saharan Africa,north,3.856,351,368.000,3,2,1,NE,17.607789,8.081666
104,Chad,Sub-Saharan Africa,north,3.763,405,651.000,15,1,1,TD,15.454166,18.732207
105,Burkina Faso,Sub-Saharan Africa,north,3.739,420,614.000,25,7,7,BF,12.238333,-1.561593
106,Madagascar,Sub-Saharan Africa,south,3.695,517,402.000,26,15,4,MG,-18.766947,46.869107
107,Liberia,Sub-Saharan Africa,north,3.622,432,455.000,19,152,2,LR,6.428055,-9.429499
108,Benin,Sub-Saharan Africa,north,3.484,512,789.000,34,4,13,BJ,9.307690,2.315834
109,Togo,Sub-Saharan Africa,north,3.303,500,577.000,36,2,19,TG,8.619543,0.824782

# Export Final DataFrame as CSV

In [40]:
final_alcohol_df.to_csv("FinalAlcohol.csv")